# Generated by Django 5.0.2 on 2024-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='users_profile/'),
        ),
    ]
